plugins {
    id('java')
    id 'net.neoforged.moddev' version '2.0.78'
}

archivesBaseName = "${mod_name}-xplat"
version = "${minecraft_version}-${build_number}"
if (System.getenv().RELEASE_MODE == null) {
    version += '-SNAPSHOT'
}

neoForge {
    // We only need MC + NeoForge classes available for compilation of the shared module.
    version = "${neoforge_version}"
    validateAccessTransformers = false

    accessTransformers = [file('src/main/resources/META-INF/accesstransformer.cfg')]

    parchment {
        minecraftVersion = '1.21.1'
        mappingsVersion = '2024.11.17'
    }
}

repositories {
    maven {
        name = "Jared" // Patchouli and JEI
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/" // for emi
    }
    maven {
        name = "Unascribed"
        url "https://repo.unascribed.com" // for ears
        content {
            includeGroup "com.unascribed"
        }
    }
}

dependencies {
    compileOnly "vazkii.patchouli:Patchouli-xplat:${minecraft_version}-93"

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.6.1'

    compileOnly "com.unascribed:ears-api:1.4.5"

    compileOnly "mezz.jei:jei-1.21.1-common-api:19.27.0.340"
    compileOnly "dev.emi:emi-xplat-mojmap:1.1.24+${minecraft_version}:api"

    compileOnly "org.jetbrains:annotations:24.0.1"
}

test {
    useJUnitPlatform()
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude 'assets/botania/patchouli_books/lexicon/en_us/README'
}

tasks.withType(JavaCompile).configureEach {
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.output_directory=${new File(rootProject.buildDir, "docsOut")}")
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.multi_source=true")

    it.options.compilerArgs << "-Xmaxerrs" << "2000"

}

processResources {
    // Exclude datagenerator .cache directory
    exclude '.cache'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}
